name: build

on:
  - push
  - pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt --yes update
      - run: sudo apt --yes install cloud-image-utils qemu
      - run: make download-image
      - run: make build
      - run: >
          qemu-system-x86_64
          -net nic
          -drive file=ubuntu-20.04-server-cloudimg-amd64.img,format=qcow2
          -drive file=user-data.img,format=raw
          -nographic
          -serial stdio
